name: Deploy Pages

run-name: ${{ github.workflow }} for ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  pages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: |
          mkdir _site
          cp .github/workflows/index.html _site/
          uv run seasons-cal -o _site/seasons-emoji.ics
          uv run seasons-cal -o _site/seasons-no-emoji.ics --no-emoji
          uv run seasons-cal -o _site/seasons-emoji-exact.ics --exact-time
          uv run seasons-cal -o _site/seasons-no-emoji-exact.ics --no-emoji --exact-time

      - uses: actions/upload-pages-artifact@v3

  pages-deploy:
    runs-on: ubuntu-latest
    needs: pages-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
