name: Release

run-name: ${{ github.workflow }} ${{ github.ref_name }}

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/seasons-cal
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Build distributables
        run: uv build

      - name: Publish to PyPI
        run: uv publish

      - name: Create release
        run: gh release create ${{ github.ref_name }} ./dist/* --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
