name: Release

run-name: ${{ github.workflow }} ${{ github.ref_name }}

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/seasons-cal
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml

      - run: python -m pip install build

      - name: Build distributables
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create release
        run: gh release create ${{ github.ref_name }} ./dist/* --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
