name: Run tests

run-name: ${{ github.workflow }} for ${{ github.ref_name }}

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Run tests
        run: uv run tests.py
